/**
 * Seed menu, recipes (bill of materials), and ingredient stock/cost.
 * KitchenStore copies this into localStorage on first run; admin edits persist.
 */
(function (root) {
  const MENU = {
    biryani: {
      id: "biryani",
      name: "Authentic Chicken Biryani",
      price: 15,
      note: "includes free raita",
      unit: "plate",
      spicy: true,
    },
    pulao: {
      id: "pulao",
      name: "Chicken Pulao",
      price: 15,
      unit: "plate",
      spicy: true,
    },
    "chicken-salan": {
      id: "chicken-salan",
      name: "Chicken Salan",
      price: 15,
      unit: "portion",
      spicy: true,
    },
    "chicken-karhai": {
      id: "chicken-karhai",
      name: "Chicken Karhai",
      price: 15,
      unit: "portion",
      spicy: true,
    },
    dumplings: {
      id: "dumplings",
      name: "Chicken Dumplings (fresh)",
      price: 20,
      note: "chilli oil sauce",
      unit: "tray",
      spicy: true,
    },
    "chicken-khao-suey": {
      id: "chicken-khao-suey",
      name: "Fresh chicken khao suey set",
      price: 40,
      unit: "set",
      spicy: true,
    },
    "chicken-pasta": {
      id: "chicken-pasta",
      name: "Fresh chicken pasta",
      price: 15,
      note: "lasagne / spaghetti / macaroni",
      unit: "portion",
      spicy: true,
    },
    "chicken-shami": {
      id: "chicken-shami",
      name: "Chicken Shami kebab (12)",
      price: 25,
      unit: "pack",
      spicy: true,
    },
    "chicken-kofta": {
      id: "chicken-kofta",
      name: "Chicken Kofta (12)",
      price: 30,
      unit: "pack",
      spicy: true,
    },
    "chicken-chapli": {
      id: "chicken-chapli",
      name: "Chicken Chapli (12)",
      price: 35,
      unit: "pack",
      spicy: true,
    },
    "dumplings-frozen": {
      id: "dumplings-frozen",
      name: "Chicken Dumplings (frozen)",
      price: 20,
      note: "chilli oil sauce",
      unit: "pack",
      spicy: true,
    },
    "beef-shami": {
      id: "beef-shami",
      name: "Beef Shami (12)",
      price: 35,
      unit: "pack",
      spicy: true,
    },
    "beef-kofta": {
      id: "beef-kofta",
      name: "Beef Kofta (12)",
      price: 35,
      unit: "pack",
      spicy: true,
    },
    "beef-chapli": {
      id: "beef-chapli",
      name: "Beef Chapli (12)",
      price: 45,
      unit: "pack",
      spicy: true,
    },
    "beef-dum-qeema": {
      id: "beef-dum-qeema",
      name: "Beef dum qeema",
      price: 45,
      unit: "portion",
      spicy: true,
    },
    "beef-khao-suey": {
      id: "beef-khao-suey",
      name: "Fresh beef khao suey set",
      price: 50,
      unit: "set",
      spicy: true,
    },
    "beef-pasta": {
      id: "beef-pasta",
      name: "Fresh beef pasta",
      price: 20,
      note: "lasagne / spaghetti / macaroni",
      unit: "portion",
      spicy: true,
    },
    "sauce-mint": { id: "sauce-mint", name: "Mint sauce", price: 10, unit: "cup" },
    "sauce-imli": { id: "sauce-imli", name: "Sweet & sour imli sauce", price: 10, unit: "cup" },
    kheer: { id: "kheer", name: "Kheer", price: 14, unit: "bowl" },
    zarda: { id: "zarda", name: "Zarda", price: 14, unit: "portion" },
    panjiri: { id: "panjiri", name: "Panjiri", price: 40, unit: "portion" },
    custard: { id: "custard", name: "Custard", price: 14, unit: "bowl" },
    truffles: { id: "truffles", name: "Truffles (6–8)", price: 18, unit: "box" },
    "shahi-tukray": { id: "shahi-tukray", name: "Shahi Tukray", price: 16, unit: "portion" },
    "dahi-baray": { id: "dahi-baray", name: "Royal Shahi Dahi Baray", price: 18, unit: "bowl" },
    pickle: { id: "pickle", name: "Sophie's Chilli Pickle", price: 28, unit: "jar" },
    "addon-charm": {
      id: "addon-charm",
      name: "Charm",
      price: 18,
      unit: "piece",
      kind: "addon",
      note: "special-order extra with biryani",
    },
    "addon-rose": {
      id: "addon-rose",
      name: "Single rose",
      price: 10,
      unit: "stem",
      kind: "addon",
      note: "special-order extra with biryani",
    },
    "addon-flowers": {
      id: "addon-flowers",
      name: "Small bouquet",
      price: 30,
      unit: "bouquet",
      kind: "addon",
      note: "special-order extra with biryani",
    },
    "plan-weekly": {
      id: "plan-weekly",
      name: "Weekly meal",
      price: 100,
      unit: "week",
      kind: "plan",
      spicy: true,
      note: "6 items · no bread",
    },
  };

  /* unitCost is RM per unit (g, ml, or pcs). */
  const INGREDIENTS = {
    basmati: { id: "basmati", name: "Basmati rice", unit: "g", onHand: 8000, unitCost: 0.012, reorderLevel: 1000 },
    chicken: { id: "chicken", name: "Chicken (halal)", unit: "g", onHand: 6000, unitCost: 0.018, reorderLevel: 800 },
    beef: { id: "beef", name: "Beef (halal)", unit: "g", onHand: 4000, unitCost: 0.032, reorderLevel: 600 },
    potato: { id: "potato", name: "Potato", unit: "g", onHand: 2000, unitCost: 0.004, reorderLevel: 400 },
    onion: { id: "onion", name: "Onion", unit: "g", onHand: 2500, unitCost: 0.004, reorderLevel: 400 },
    yogurt: { id: "yogurt", name: "Yogurt", unit: "g", onHand: 2500, unitCost: 0.008, reorderLevel: 500 },
    cucumber: { id: "cucumber", name: "Cucumber", unit: "g", onHand: 600, unitCost: 0.006, reorderLevel: 150 },
    ghee: { id: "ghee", name: "Ghee / cooking oil", unit: "ml", onHand: 2500, unitCost: 0.022, reorderLevel: 400 },
    "biryani-masala": { id: "biryani-masala", name: "Biryani masala", unit: "g", onHand: 250, unitCost: 0.08, reorderLevel: 40 },
    saffron: { id: "saffron", name: "Saffron", unit: "g", onHand: 2, unitCost: 40, reorderLevel: 0.4 },
    cilantro: { id: "cilantro", name: "Cilantro / mint", unit: "g", onHand: 250, unitCost: 0.02, reorderLevel: 40 },
    lime: { id: "lime", name: "Lime", unit: "pcs", onHand: 24, unitCost: 0.4, reorderLevel: 6 },
    salt: { id: "salt", name: "Salt", unit: "g", onHand: 1500, unitCost: 0.002, reorderLevel: 200 },
    "green-chilli": { id: "green-chilli", name: "Green chilli", unit: "g", onHand: 1500, unitCost: 0.012, reorderLevel: 300 },
    "mustard-oil": { id: "mustard-oil", name: "Mustard oil", unit: "ml", onHand: 1000, unitCost: 0.025, reorderLevel: 200 },
    "mustard-seed": { id: "mustard-seed", name: "Mustard seed", unit: "g", onHand: 300, unitCost: 0.03, reorderLevel: 50 },
    "pickle-spices": { id: "pickle-spices", name: "Pickle spices (fennel, nigella, fenugreek, turmeric)", unit: "g", onHand: 220, unitCost: 0.045, reorderLevel: 40 },
    "gram-flour": { id: "gram-flour", name: "Urad / gram flour (besan)", unit: "g", onHand: 1800, unitCost: 0.012, reorderLevel: 300 },
    flour: { id: "flour", name: "Wheat flour", unit: "g", onHand: 2500, unitCost: 0.006, reorderLevel: 400 },
    tamarind: { id: "tamarind", name: "Tamarind", unit: "g", onHand: 400, unitCost: 0.02, reorderLevel: 60 },
    "chaat-masala": { id: "chaat-masala", name: "Chaat masala / dahi spices", unit: "g", onHand: 150, unitCost: 0.05, reorderLevel: 30 },
    bread: { id: "bread", name: "Bread", unit: "pcs", onHand: 24, unitCost: 0.4, reorderLevel: 6 },
    milk: { id: "milk", name: "Milk", unit: "ml", onHand: 2500, unitCost: 0.006, reorderLevel: 400 },
    sugar: { id: "sugar", name: "Sugar", unit: "g", onHand: 2500, unitCost: 0.004, reorderLevel: 400 },
    pistachio: { id: "pistachio", name: "Pistachios / mixed nuts", unit: "g", onHand: 250, unitCost: 0.12, reorderLevel: 30 },
    cardamom: { id: "cardamom", name: "Cardamom", unit: "g", onHand: 50, unitCost: 0.15, reorderLevel: 8 },
    "chilli-oil": { id: "chilli-oil", name: "Chilli oil sauce", unit: "ml", onHand: 600, unitCost: 0.03, reorderLevel: 80 },
    lentils: { id: "lentils", name: "Masoor / moong dal", unit: "g", onHand: 2000, unitCost: 0.008, reorderLevel: 300 },
    tomato: { id: "tomato", name: "Tomato", unit: "g", onHand: 1500, unitCost: 0.006, reorderLevel: 250 },
    charm: { id: "charm", name: "Keepsake charm (bought)", unit: "pcs", onHand: 20, unitCost: 7, reorderLevel: 4 },
    rose: { id: "rose", name: "Single rose (bought)", unit: "pcs", onHand: 12, unitCost: 5, reorderLevel: 3 },
    bouquet: { id: "bouquet", name: "Small mixed bouquet (bought)", unit: "pcs", onHand: 6, unitCost: 15, reorderLevel: 2 },
    "kraft-wrap": { id: "kraft-wrap", name: "Kraft wrap + ribbon", unit: "pcs", onHand: 30, unitCost: 1.5, reorderLevel: 8 },
    pasta: { id: "pasta", name: "Pasta (lasagne / spaghetti / macaroni)", unit: "g", onHand: 2500, unitCost: 0.008, reorderLevel: 400 },
    cheese: { id: "cheese", name: "Cheese", unit: "g", onHand: 800, unitCost: 0.028, reorderLevel: 120 },
    noodles: { id: "noodles", name: "Egg noodles", unit: "g", onHand: 1800, unitCost: 0.01, reorderLevel: 300 },
    "coconut-milk": { id: "coconut-milk", name: "Coconut milk", unit: "ml", onHand: 1500, unitCost: 0.012, reorderLevel: 250 },
    cocoa: { id: "cocoa", name: "Cocoa powder", unit: "g", onHand: 250, unitCost: 0.04, reorderLevel: 40 },
    "milk-powder": { id: "milk-powder", name: "Milk powder", unit: "g", onHand: 800, unitCost: 0.025, reorderLevel: 120 },
    "custard-powder": { id: "custard-powder", name: "Custard powder", unit: "g", onHand: 400, unitCost: 0.018, reorderLevel: 60 },
    fruit: { id: "fruit", name: "Mixed fruit", unit: "g", onHand: 600, unitCost: 0.008, reorderLevel: 120 },
    egg: { id: "egg", name: "Egg", unit: "pcs", onHand: 24, unitCost: 0.5, reorderLevel: 6 },
  };

  const kebabMix = (meatId, meatQty) => [
    { ingredientId: meatId, qty: meatQty },
    { ingredientId: "onion", qty: 40 },
    { ingredientId: "gram-flour", qty: 25 },
    { ingredientId: "salt", qty: 3 },
    { ingredientId: "ghee", qty: 15 },
  ];

  const dumplingMix = (frozen) => [
    { ingredientId: "chicken", qty: frozen ? 280 : 280 },
    { ingredientId: "flour", qty: 180 },
    { ingredientId: "onion", qty: 40 },
    { ingredientId: "cilantro", qty: 12 },
    { ingredientId: "green-chilli", qty: 12 },
    { ingredientId: "ghee", qty: 12 },
    { ingredientId: "chilli-oil", qty: 40 },
    { ingredientId: "salt", qty: 3 },
  ];

  const RECIPES = {
    biryani: [
      { ingredientId: "basmati", qty: 180 },
      { ingredientId: "chicken", qty: 200 },
      { ingredientId: "potato", qty: 80 },
      { ingredientId: "onion", qty: 50 },
      { ingredientId: "yogurt", qty: 40 },
      { ingredientId: "ghee", qty: 25 },
      { ingredientId: "biryani-masala", qty: 8 },
      { ingredientId: "saffron", qty: 0.05 },
      { ingredientId: "cilantro", qty: 8 },
      { ingredientId: "lime", qty: 1 },
      { ingredientId: "salt", qty: 3 },
      { ingredientId: "yogurt", qty: 80 },
      { ingredientId: "cucumber", qty: 30 },
      { ingredientId: "salt", qty: 1 },
    ],
    pulao: [
      { ingredientId: "basmati", qty: 180 },
      { ingredientId: "chicken", qty: 180 },
      { ingredientId: "onion", qty: 40 },
      { ingredientId: "ghee", qty: 20 },
      { ingredientId: "biryani-masala", qty: 5 },
      { ingredientId: "salt", qty: 3 },
    ],
    "chicken-salan": [
      { ingredientId: "chicken", qty: 220 },
      { ingredientId: "onion", qty: 60 },
      { ingredientId: "yogurt", qty: 40 },
      { ingredientId: "ghee", qty: 20 },
      { ingredientId: "biryani-masala", qty: 8 },
      { ingredientId: "salt", qty: 3 },
    ],
    "chicken-karhai": [
      { ingredientId: "chicken", qty: 220 },
      { ingredientId: "onion", qty: 50 },
      { ingredientId: "green-chilli", qty: 20 },
      { ingredientId: "ghee", qty: 25 },
      { ingredientId: "biryani-masala", qty: 6 },
      { ingredientId: "salt", qty: 3 },
    ],
    dumplings: dumplingMix(false),
    "dumplings-frozen": dumplingMix(true),
    "chicken-khao-suey": [
      { ingredientId: "noodles", qty: 180 },
      { ingredientId: "chicken", qty: 220 },
      { ingredientId: "coconut-milk", qty: 200 },
      { ingredientId: "onion", qty: 50 },
      { ingredientId: "ghee", qty: 15 },
      { ingredientId: "chilli-oil", qty: 20 },
      { ingredientId: "cilantro", qty: 10 },
      { ingredientId: "lime", qty: 1 },
      { ingredientId: "biryani-masala", qty: 6 },
      { ingredientId: "salt", qty: 3 },
    ],
    "chicken-pasta": [
      { ingredientId: "pasta", qty: 180 },
      { ingredientId: "chicken", qty: 180 },
      { ingredientId: "tomato", qty: 80 },
      { ingredientId: "onion", qty: 40 },
      { ingredientId: "cheese", qty: 40 },
      { ingredientId: "milk", qty: 40 },
      { ingredientId: "ghee", qty: 15 },
      { ingredientId: "salt", qty: 3 },
    ],
    "chicken-shami": kebabMix("chicken", 360),
    "chicken-kofta": kebabMix("chicken", 400),
    "chicken-chapli": [
      { ingredientId: "chicken", qty: 420 },
      { ingredientId: "onion", qty: 50 },
      { ingredientId: "flour", qty: 30 },
      { ingredientId: "ghee", qty: 25 },
      { ingredientId: "salt", qty: 3 },
    ],
    "beef-shami": kebabMix("beef", 360),
    "beef-kofta": kebabMix("beef", 400),
    "beef-chapli": [
      { ingredientId: "beef", qty: 420 },
      { ingredientId: "onion", qty: 50 },
      { ingredientId: "flour", qty: 30 },
      { ingredientId: "ghee", qty: 25 },
      { ingredientId: "salt", qty: 3 },
    ],
    "beef-dum-qeema": [
      { ingredientId: "beef", qty: 350 },
      { ingredientId: "onion", qty: 60 },
      { ingredientId: "ghee", qty: 25 },
      { ingredientId: "biryani-masala", qty: 8 },
      { ingredientId: "salt", qty: 3 },
    ],
    "beef-khao-suey": [
      { ingredientId: "noodles", qty: 180 },
      { ingredientId: "beef", qty: 240 },
      { ingredientId: "coconut-milk", qty: 200 },
      { ingredientId: "onion", qty: 50 },
      { ingredientId: "ghee", qty: 15 },
      { ingredientId: "chilli-oil", qty: 20 },
      { ingredientId: "cilantro", qty: 10 },
      { ingredientId: "lime", qty: 1 },
      { ingredientId: "biryani-masala", qty: 6 },
      { ingredientId: "salt", qty: 3 },
    ],
    "beef-pasta": [
      { ingredientId: "pasta", qty: 180 },
      { ingredientId: "beef", qty: 200 },
      { ingredientId: "tomato", qty: 80 },
      { ingredientId: "onion", qty: 40 },
      { ingredientId: "cheese", qty: 40 },
      { ingredientId: "milk", qty: 40 },
      { ingredientId: "ghee", qty: 15 },
      { ingredientId: "salt", qty: 3 },
    ],
    "sauce-mint": [
      { ingredientId: "cilantro", qty: 40 },
      { ingredientId: "green-chilli", qty: 8 },
      { ingredientId: "lime", qty: 1 },
      { ingredientId: "salt", qty: 1 },
    ],
    "sauce-imli": [
      { ingredientId: "tamarind", qty: 40 },
      { ingredientId: "sugar", qty: 15 },
      { ingredientId: "salt", qty: 1 },
    ],
    pickle: [
      { ingredientId: "green-chilli", qty: 250 },
      { ingredientId: "mustard-oil", qty: 150 },
      { ingredientId: "mustard-seed", qty: 20 },
      { ingredientId: "pickle-spices", qty: 20 },
      { ingredientId: "salt", qty: 12 },
    ],
    "dahi-baray": [
      { ingredientId: "gram-flour", qty: 80 },
      { ingredientId: "yogurt", qty: 250 },
      { ingredientId: "tamarind", qty: 15 },
      { ingredientId: "chaat-masala", qty: 6 },
      { ingredientId: "ghee", qty: 40 },
      { ingredientId: "onion", qty: 20 },
      { ingredientId: "salt", qty: 3 },
    ],
    "shahi-tukray": [
      { ingredientId: "bread", qty: 3 },
      { ingredientId: "milk", qty: 250 },
      { ingredientId: "sugar", qty: 40 },
      { ingredientId: "ghee", qty: 30 },
      { ingredientId: "pistachio", qty: 8 },
      { ingredientId: "saffron", qty: 0.03 },
      { ingredientId: "cardamom", qty: 1 },
    ],
    kheer: [
      { ingredientId: "basmati", qty: 40 },
      { ingredientId: "milk", qty: 280 },
      { ingredientId: "sugar", qty: 30 },
      { ingredientId: "pistachio", qty: 8 },
      { ingredientId: "cardamom", qty: 1 },
    ],
    zarda: [
      { ingredientId: "basmati", qty: 140 },
      { ingredientId: "sugar", qty: 40 },
      { ingredientId: "ghee", qty: 20 },
      { ingredientId: "saffron", qty: 0.03 },
      { ingredientId: "pistachio", qty: 8 },
      { ingredientId: "cardamom", qty: 1 },
    ],
    panjiri: [
      { ingredientId: "flour", qty: 80 },
      { ingredientId: "ghee", qty: 40 },
      { ingredientId: "pistachio", qty: 20 },
      { ingredientId: "sugar", qty: 20 },
      { ingredientId: "cardamom", qty: 1 },
    ],
    custard: [
      { ingredientId: "milk", qty: 250 },
      { ingredientId: "custard-powder", qty: 20 },
      { ingredientId: "sugar", qty: 25 },
      { ingredientId: "cardamom", qty: 1 },
      { ingredientId: "fruit", qty: 60 },
      { ingredientId: "egg", qty: 1 },
    ],
    truffles: [
      { ingredientId: "milk-powder", qty: 60 },
      { ingredientId: "cocoa", qty: 15 },
      { ingredientId: "ghee", qty: 20 },
      { ingredientId: "sugar", qty: 20 },
      { ingredientId: "pistachio", qty: 10 },
      { ingredientId: "cardamom", qty: 0.5 },
    ],
    /* Default weekly box: chicken biryani, mix veg, daal tadka, chicken qorma, chicken aloo qeema, zeera rice. */
    "plan-weekly": [
      { ingredientId: "basmati", qty: 180 },
      { ingredientId: "chicken", qty: 200 },
      { ingredientId: "potato", qty: 80 },
      { ingredientId: "onion", qty: 50 },
      { ingredientId: "yogurt", qty: 120 },
      { ingredientId: "ghee", qty: 25 },
      { ingredientId: "biryani-masala", qty: 8 },
      { ingredientId: "saffron", qty: 0.05 },
      { ingredientId: "cilantro", qty: 8 },
      { ingredientId: "lime", qty: 1 },
      { ingredientId: "salt", qty: 4 },
      { ingredientId: "cucumber", qty: 30 },
      { ingredientId: "potato", qty: 200 },
      { ingredientId: "onion", qty: 40 },
      { ingredientId: "tomato", qty: 40 },
      { ingredientId: "ghee", qty: 20 },
      { ingredientId: "salt", qty: 3 },
      { ingredientId: "lentils", qty: 120 },
      { ingredientId: "onion", qty: 30 },
      { ingredientId: "tomato", qty: 30 },
      { ingredientId: "ghee", qty: 15 },
      { ingredientId: "biryani-masala", qty: 4 },
      { ingredientId: "salt", qty: 3 },
      { ingredientId: "chicken", qty: 220 },
      { ingredientId: "onion", qty: 60 },
      { ingredientId: "yogurt", qty: 40 },
      { ingredientId: "ghee", qty: 20 },
      { ingredientId: "biryani-masala", qty: 8 },
      { ingredientId: "salt", qty: 3 },
      { ingredientId: "chicken", qty: 180 },
      { ingredientId: "potato", qty: 80 },
      { ingredientId: "onion", qty: 40 },
      { ingredientId: "ghee", qty: 20 },
      { ingredientId: "biryani-masala", qty: 6 },
      { ingredientId: "salt", qty: 3 },
      { ingredientId: "basmati", qty: 150 },
      { ingredientId: "ghee", qty: 15 },
      { ingredientId: "salt", qty: 2 },
    ],
    "addon-charm": [
      { ingredientId: "charm", qty: 1 },
      { ingredientId: "kraft-wrap", qty: 1 },
    ],
    "addon-rose": [
      { ingredientId: "rose", qty: 1 },
      { ingredientId: "kraft-wrap", qty: 1 },
    ],
    "addon-flowers": [
      { ingredientId: "bouquet", qty: 1 },
      { ingredientId: "kraft-wrap", qty: 1 },
    ],
  };

  /* KL retail notes for admin costing. promoWas = old list price still shown on the public card. */
  const COSTING_META = {
    biryani: { promoWas: 32, klNote: "KL stall/home plate often RM 12–22; sit-down dum RM 18–28. RM 15 is a promo (was 32)." },
    pulao: { klNote: "Home/stall rice plates RM 10–18." },
    "chicken-salan": { klNote: "Home curry portion RM 10–18." },
    "chicken-karhai": { klNote: "Karhai plates RM 12–22." },
    dumplings: { klNote: "Fresh 12-pc trays ~RM 15–25." },
    "chicken-khao-suey": { klNote: "Khao suey / khaosuay sets ~RM 28–48." },
    "chicken-pasta": { klNote: "Home pasta plates RM 12–20." },
    "dumplings-frozen": { klNote: "Frozen dumpling packs ~RM 15–25." },
    "chicken-shami": { klNote: "Frozen chicken kebab packs (12) ~RM 20–32." },
    "chicken-kofta": { klNote: "Frozen kofta packs ~RM 25–38." },
    "chicken-chapli": { klNote: "Chapli packs sit higher, ~RM 28–42." },
    "beef-shami": { klNote: "Frozen beef kebab packs ~RM 30–42." },
    "beef-kofta": { klNote: "Beef kofta packs ~RM 30–42." },
    "beef-chapli": { klNote: "Beef chapli packs ~RM 38–55." },
    "beef-dum-qeema": { klNote: "Home beef qeema portions ~RM 28–48." },
    "beef-khao-suey": { klNote: "Beef khao suey sets ~RM 35–55." },
    "beef-pasta": { klNote: "Home beef pasta plates RM 16–24." },
    "sauce-mint": { klNote: "Grocery / homemade cups ~RM 8–15." },
    "sauce-imli": { klNote: "Grocery / homemade cups ~RM 8–15." },
    kheer: { klNote: "Dessert bowls ~RM 8–18." },
    zarda: { klNote: "Sweet rice portions ~RM 10–18." },
    panjiri: { klNote: "Dessert scoops RM 12–18; homemade jars often RM 25–45. RM 40 is specialty, not leftover." },
    custard: { klNote: "Fruit custard bowls ~RM 10–16. Priced with kheer at RM 14." },
    truffles: { klNote: "Homemade chocolate truffle boxes (6–8) ~RM 15–25." },
    "shahi-tukray": { klNote: "Shahi tukra bowls ~RM 12–20." },
    "dahi-baray": { klNote: "Dahi bhalla bowls ~RM 10–20." },
    pickle: { klNote: "Homemade chilli achar jars ~RM 15–35." },
    "addon-charm": { klNote: "Bought keepsake + wrap; not food." },
    "addon-rose": { klNote: "KL single rose often RM 4–8 landed." },
    "addon-flowers": { klNote: "Small mixed bunch often RM 12–20 landed." },
    "plan-weekly": { klNote: "KL home tiffin / weekly boxes ~RM 80–150." },
  };

  root.LazzatData = { MENU, INGREDIENTS, RECIPES, COSTING_META };
})(window);
